apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: app-dpdt
    app: app
  name: app
  namespace: diplom

spec:
  ports:
  - name: 80-3003
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: app
  type: LoadBalancer
  externalIPs:
    - 158.160.73.61
    - 158.160.75.211
status:
  loadBalancer: {}

